services:
  postgres:
    container_name: postgres-sql-sbn
    image: postgres
    environment:
      POSTGRES_USER: username # ajoutez un nom d'utilisateur
      POSTGRES_PASSWORD: password # ajoutez un mot de passe
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: book_social_network
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - spring-demo
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-sbn
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - spring-demo

  book-network-api:
    build:
      context: ./book-network
      dockerfile: Dockerfile
    container_name: book-network-api
    ports:
      - "8088:8088"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/book_social_network
      - SPRING_DATASOURCE_USERNAME=username
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_MAIL_HOST=mail-dev
    depends_on:
      - postgres
      - mail-dev
    networks:
      - spring-demo
    restart: unless-stopped

volumes:
  postgres:
    driver: local

networks:
  spring-demo:
    driver: bridge
